export type Smartphone = {
    id: number,
    title: string,
    slug: string,
    category: "Flagship" | "Mid-range" | "Budget",
    brand: string,
    price: number,
    display: string,
    cpu: string,
    ram: number,
    storage: number,
    battery: number,
    camera: string,
    os: string,
    image: string,
};
